Music_box_v02/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda r:redirect('musicbox:musicbox_home'), name='root'),
    path('admin/', admin.site.urls),
    path('musicbox/', include("musicbox.urls", namespace="musicbox")),
]

musicbox/urls.py
from django.urls import path
from . import views

app_name = "musicbox"

urlpatterns = [
    path('', views.musicbox_home, name="musicbox_home"),
    path('search/result', views.search_result, name="search_result"),

    path('<str:kind>', views.kind_list, name="kind_list"),
    path('<str:kind>/<int:pk>', views.kind_detail, name="kind_detail"),
]

musicbox/models.py
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50, help_text='Enter a song gerne (e.g. Hiphop)')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre_detail', args=[str(self.name)])


class Artist(models.Model):
    """Model representing an author."""
    name = models.CharField(max_length=50)
    real_name = models.CharField(max_length=50)
    another_name = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('artist_detail', args=[str(self.name)])

    def __str__(self):
        return self.name


class Song(models.Model):
    title = models.CharField(max_length=200)
    artist = models.ManyToManyField(Artist)
    link = models.CharField(max_length=1000, help_text='Enter a youtube video ID of this song')
    genre = models.ForeignKey('Genre', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'genre']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('song_detail', args=[str(self.id)])


class Playlist(models.Model):
    name = models.CharField(max_length=100)
    explanation = models.TextField(max_length=1000, help_text='Enter a explanation of this song')
    songs = models.ManyToManyField(Song, help_text='Select a songs for this playlist')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('playlist_detail', args=[str(self.id)])

musicbox/forms.py
from django import forms

musicbox/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Song, Artist, Genre, Playlist

# Create your views here.
def musicbox_home(request):
    context = {
        'song_count' : Song.objects.all().count(), 
        'artist_count' : Artist.objects.all().count(),
        'genre_count' : Genre.objects.all().count(),
        'playlist_count' : Playlist.objects.all().count(),
    }
    return render(request, "musicbox/musicbox_home.html", context=context)

def kind_list(request, kind):
    if kind=='song':
        contexts = Song.objects.all()
        PAGE_ROW_COUNT = 6
    elif kind=='artist':
        contexts = Artist.objects.all()
        PAGE_ROW_COUNT = 10
    elif kind=='genre':
        contexts = Genre.objects.all()
        PAGE_ROW_COUNT = 10
    elif kind=='playlist':
        contexts = Playlist.objects.all()
        PAGE_ROW_COUNT = 10
    else:
        return redirect("musicbox:musicbox_home")
    
    PAGE_DISPLAY_COUNT = 10
    
    paginator=Paginator(contexts, PAGE_ROW_COUNT)
    pageNum=request.GET.get('pageNum') # 현제 페이지
    
    totalPageCount=paginator.num_pages # 전체 페이지 갯수 
    
    try:
        contexts = paginator.page(pageNum)
    except PageNotAnInteger:
        contexts = paginator.page(1)
        pageNum = 1
    except EmptyPage:
        contexts = paginator.page(paginator.num_pages)
        pageNum = paginator.num_pages
        
    pageNum = int(pageNum)
    
    startPageNum = 1 + PAGE_DISPLAY_COUNT * int((pageNum - 1)/PAGE_DISPLAY_COUNT)
    endPageNum = startPageNum + PAGE_DISPLAY_COUNT-1

    if totalPageCount < endPageNum:
        endPageNum = totalPageCount
        
    bottomPages = range(startPageNum, endPageNum+1)
    
    return render(request, f"musicbox/{kind}_list.html", {
            f'{kind}s':contexts,
            'pageNum':pageNum,
            'bottomPages':bottomPages,
            'totalPageCount':totalPageCount,
            'startPageNum':startPageNum,
            'endPageNum':endPageNum,
        }
    )

def kind_detail(request, kind, pk):
    if kind=='song':
        context = get_object_or_404(Song, pk=pk)
        playlists = Playlist.objects.filter(songs=context)
        return render(request, f"musicbox/{kind}_detail.html", {
            f'{kind}':context,
            'playlists' : playlists,
        })
    elif kind=='artist':
        context = get_object_or_404(Artist, pk=pk)
        songs = Song.objects.filter(artist=context)
    elif kind=='genre':
        context = get_object_or_404(Genre, pk=pk)
        songs = Song.objects.filter(genre=context)
    elif kind=='playlist':
        context = get_object_or_404(Playlist, pk=pk)
        songs = context.songs.all()
        print(songs)
    else:
        return redirect("musicbox:musicbox_home")

    PAGE_ROW_COUNT = 6
    PAGE_DISPLAY_COUNT = 10

    paginator=Paginator(songs, PAGE_ROW_COUNT)
    pageNum=request.GET.get('pageNum') # 현제 페이지
    totalPageCount=paginator.num_pages # 전체 페이지 갯수 
    
    try:
        songs = paginator.page(pageNum)
    except PageNotAnInteger:
        songs = paginator.page(1)
        pageNum = 1
    except EmptyPage:
        songs = paginator.page(paginator.num_pages)
        pageNum = paginator.num_pages
        
    pageNum = int(pageNum)
    
    startPageNum = 1 + PAGE_DISPLAY_COUNT * int((pageNum - 1)/PAGE_DISPLAY_COUNT)
    endPageNum = startPageNum + PAGE_DISPLAY_COUNT-1
    if totalPageCount < endPageNum:
        endPageNum = totalPageCount
        
    bottomPages = range(startPageNum, endPageNum+1)
    
    return render(request, f"musicbox/{kind}_detail.html", {
            f'{kind}': context,
            'songs' : songs,
            'pageNum':pageNum,
            'bottomPages':bottomPages,
            'totalPageCount':totalPageCount,
            'startPageNum':startPageNum,
            'endPageNum':endPageNum,
        }
    )
    
def search_result(request):
    q = request.GET['q']
    songs = Song.objects.filter(title__contains=q)
    artists = Artist.objects.filter(name__contains=q) | Artist.objects.filter(real_name__contains=q) | Artist.objects.filter(another_name__contains=q)
    genres = Genre.objects.filter(name__contains=q)
    playlists = Playlist.objects.filter(name__contains=q) | Playlist.objects.filter(explanation__contains=q)

    return render(request, "musicbox/search_result.html", {
        'songs' : songs,
        'artists' : artists,
        'genres' : genres,
        'playlists' : playlists,
        'q' : q,
    })

musicbox/templates/musicbox/artist_detail.html
{% extends 'musicbox/base.html' %}

{% block title %}
Artist Detail
{% endblock %}

{% block content %}
<div class="col-12 jumbotron m-0 p-4 my-1">
    <h1 class="display-5 artist-name m-0">{{ artist.name }} <small>({{ artist.real_name }} )</small></h1>
</div>
{% include 'musicbox/card_style.html' %}

<div class="col-12">
        {% include 'musicbox/pagination.html' %}
        </div>

{% endblock %}

musicbox/templates/musicbox/artist_list.html
{% extends 'musicbox/base.html' %}

{% block title %}
Artist List
{% endblock %}

{% block content %}
<div class="p-2 m-3">
    <h1 class="kind-title display-5">Artist List</h1>
</div>
<div class="col-md-12 col-lg-6">
    <table class="table table-hover mt-2 border-bottom">
        <thead>
            <tr class="thead-light" style="">
                <th width="75%">Name</th>
                <th>Songs</th>
            </tr>
        </thead>
        <tbody>
            {% for artist in artists %}
            <tr>
                <td><a href="{% url 'musicbox:kind_detail' 'artist' artist.id %}">{{ artist.name }}</a></td>
                <td>{{ artist.song_set.all.count }} songs</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'musicbox/pagination.html' %}
</div>

{% endblock %}

musicbox/templates/musicbox/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'style.css' %}">


    <link href="https://fonts.googleapis.com/css?family=Roboto:400i,900i,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,900,700&display=swap" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
        <a class="navbar-brand" href="{% url 'musicbox:musicbox_home' %}">
            <img src="/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30"
                class="d-inline-block align-top" alt="">
            Music Box
        </a>

        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0 w-75 d-flex justify-content-end" method="get" action="{% url 'musicbox:search_result' %}">
                <input class="form-control mr-sm-2 d-inline-flex w-50" type="text" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-light my-2 my-sm-0 d-inline-flex" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <section class="row m-1">
        <div class="col-sm-12 col-md-2 p-0">
            <div id="list-group" class="w-100">
                <a href="{% url 'musicbox:kind_list' 'song' %}" class="list-group-item list-group-item-action">Songs</a>
                <a href="{% url 'musicbox:kind_list' 'artist' %}"
                    class="list-group-item list-group-item-action">Artists</a>
                <a href="{% url 'musicbox:kind_list' 'genre' %}"
                    class="list-group-item list-group-item-action">Genres</a>
                <a href="{% url 'musicbox:kind_list' 'playlist' %}"
                    class="list-group-item list-group-item-action">Playlists</a>
            </div>
        </div>
        <div class="col-sm-12 col-md-10">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
    <hr>
    <footer class="container">
        <div class="row">
            <div class="col-12 mb-5">
                <h6 class="text-right"><a href="https://github.com/choibumsu">&copy; Choi Teemo</a></h6>
            </div>
        </div>
    </footer>
</body>

</html>

musicbox/templates/musicbox/card_style.html
<div class="row">
    {% for song in songs %}
    <div class="col-md-12 col-lg-6 d-inline-flex m-0 p-1">
        <div class="card w-100">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'musicbox:kind_detail' 'song' song.id %}">{{ song.title }}</a>
                </h5>
                <hr>
                <p class="card-text text-right">
                    {% for artist in song.artist.all %}
                    <a
                        href="{% url 'musicbox:kind_detail' 'artist' artist.id %}">{{ artist }}</a>{% if not forloop.last %},
                    {% endif %}{% endfor %}<br />
                    <a href="{% url 'musicbox:kind_detail' 'genre' song.genre.id %}">{{ song.genre }}</a><br />
                </p>
                <div style="position:relative;padding-top:56.25%;">
                    <iframe id="{{song.id}}" frameborder="0" allowfullscreen="1"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        title="YouTube video player" src="https://www.youtube.com/embed/{{ song.link }}"
                        style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

musicbox/templates/musicbox/genre_detail.html
{% extends 'musicbox/base.html' %}

{% block title %}
Genre Detail
{% endblock %}

{% block content %}
<div class="col-12 jumbotron m-0 p-4 my-1">
    <h1 class="display-5 artist-name m-0">{{ genre.name }}</h1>
</div>
{% include 'musicbox/card_style.html' %}

<div class="col-12">
        {% include 'musicbox/pagination.html' %}
        </div>

{% endblock %}

musicbox/templates/musicbox/genre_list.html
{% extends 'musicbox/base.html' %}

{% block title %}
Genre List
{% endblock %}

{% block content %}
<div class="p-2 m-3">
    <h1 class="kind-title display-5">Genre List</h1>
</div>
<div class="col-md-12 col-lg-6">
    <table class="table table-hover mt-2 border-bottom">
        <thead>
            <tr class="thead-light" style="">
                <th width="75%">Genre</th>
                <th>Songs</th>
            </tr>
        </thead>
        <tbody>
            {% for genre in genres %}
            <tr>
                <td><a href="{% url 'musicbox:kind_detail' 'genre' genre.id %}">{{ genre.name }}</a></td>
                <td>{{ genre.song_set.all.count }} songs</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% include 'musicbox/pagination.html' %}
</div>
{% endblock %}

musicbox/templates/musicbox/musicbox_home.html
{% extends 'musicbox/base.html' %}

{% block title %}
Music Box Home
{% endblock %}

{% block content %}
<div class="jumbotron py-2 mt-3">
    <h1 class="kind-title display-4"><a href="{% url 'musicbox:kind_list' 'song' %}">Songs</a></h1>
    <p class="lead">{{ song_count }} songs</p>
    <hr>
</div>
<div class="jumbotron py-2">
    <h1 class="kind-title display-4"><a href="{% url 'musicbox:kind_list' 'artist' %}">Artists</a></h1>
    <p class="lead">{{ artist_count }} artists</p>
    <hr>
</div>
<div class="jumbotron py-2">
    <h1 class="kind-title display-4"><a href="{% url 'musicbox:kind_list' 'genre' %}">Genres</a></h1>
    <p class="lead">{{ genre_count }} genres</p>
    <hr>
</div>
<div class="jumbotron py-2">
    <h1 class="kind-title display-4"><a href="{% url 'musicbox:kind_list' 'playlist' %}">Playlists</a></h1>
    <p class="lead">{{ playlist_count }} playlists</p>
    <hr>
</div>

{% endblock %}

musicbox/templates/musicbox/pagination.html
{% load mathfilters %}
{% if endPageNum != 1 %}
<div class="page_display d-flex justify-content-center my-4" aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item">
            {% if startPageNum != 1 %}
            <a class="page-link px-0" href="?pageNum={{startPageNum | sub:1}}" aria-label="Start"><span
                    aria-hidden="true">&laquo;</span></a>
            {% else %}
            <a class="page-link px-0" aria-label="Start"><span aria-hidden="true" style="color:white;">-</span></a>
            {% endif %}
        </li>
        <li class="page-item">
            {% if pageNum != 1 %}
            <a class="page-link px-0" href="?pageNum={{pageNum | sub:1}}" aria-label="Previous"><span
                    aria-hidden="true">&lt;</span></a>
            {% else %}
            <a class="page-link px-0" aria-label="Previous"><span
                aria-hidden="true" style="color:white;">-</span></a>
            {% endif %}
        </li>

        {% for i in bottomPages %}
        <li class="page-item">
            {% if i == pageNum %}
            <a class="page-link px-0" href="?pageNum={{i}}"><strong>{{i}}</strong></a>
            {% else %}
            <a class="page-link px-0" href="?pageNum={{i}}">{{i}}</a>
            {% endif %}
        </li>
        {% endfor %}

        <li class="page-item">
                {% if pageNum < totalPageCount %}
            <a class="page-link px-0" href="?pageNum={{pageNum | add:1}}" aria-label="Next"><span
                    aria-hidden="true">&gt;</span></a>
            {% else %}
            <a class="page-link px-0" aria-label="Next"><span
                aria-hidden="true" style="color:white;">-</span></a>
            {% endif %}
        </li>
        <li class="page-item">
            {% if endPageNum < totalPageCount %}
            <a class="page-link px-0" href="?pageNum={{endPageNum | add:1}}" aria-label="End"><span
                    aria-hidden="true">&raquo;</span></a>
            {% else %}
            <a class="page-link px-0" aria-label="End"><span
                aria-hidden="true" style="color:white;">-</span></a>
            {% endif %}
        </li>
    </ul>
</div>
{% endif %}

musicbox/templates/musicbox/playlist_detail.html
{% extends 'musicbox/base.html' %}

{% block title %}
Playlist Detail
{% endblock %}

{% block content %}
<div class="col-12 jumbotron m-0 p-4 my-1">
    <h1 class="display-5 artist-name m-0">{{ playlist.name }}</h1>
    <p class="mt-3 mb-0">{{ playlist.explanation }}</p>
</div>
{% include 'musicbox/card_style.html' %}

<div class="col-12">
    {% include 'musicbox/pagination.html' %}
</div>

{% endblock %}

musicbox/templates/musicbox/playlist_list.html
{% extends 'musicbox/base.html' %}

{% block title %}
Playlist List
{% endblock %}

{% block content %}
<div class="p-2 m-3">
    <h1 class="kind-title display-5">Playlist List</h1>
</div>
<div class="col-md-12 col-lg-6">
    <table class="table table-hover mt-2 border-bottom">
        <thead>
            <tr class="thead-light" style="">
                <th width="75%">Playlist</th>
                <th>Songs</th>
            </tr>
        </thead>
        <tbody>
            {% for playlist in playlists %}
            <tr>
                <td><a href="{% url 'musicbox:kind_detail' 'playlist' playlist.id %}">{{ playlist.name }}</a></td>
                <td>{{ playlist.songs.count }} songs</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% include 'musicbox/pagination.html' %}
</div>
{% endblock %}

musicbox/templates/musicbox/search_result.html
{% extends 'musicbox/base.html' %}

{% block title %}
Search Result
{% endblock %}

{% block content %}
<div class="p-2 m-3">
        <h1 class="kind-title display-5">'{{ q }}' <small>검색결과</small></h1>
    </div>
    <hr>
    <div class="col-md-12 col-lg-8">
        <h5>Songs<small> : {{ songs.count }}개의 검색결과</small></h5>
        <table class="table table-hover mt-2 border-bottom">
            <thead>
                <tr class="thead-light" style="">
                    <th width="50%">Title</th>
                    <th>Artist</th>
                </tr>
            </thead>
            <tbody>
                {% for song in songs %}
                <tr>
                    <td><a href="{% url 'musicbox:kind_detail' 'song' song.id %}">{{ song.title }}</a></td>
                    <td>
                        {% for artist in song.artist.all %}
                            <a href="{% url 'musicbox:kind_detail' 'artist' artist.id %}">{{ artist }}</a>
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
    <div class="col-md-12 col-lg-8">
        <h5>Artists<small> : {{ artists.count }}개의 검색결과</small></h5>
        <table class="table table-hover mt-2 border-bottom">
            <thead>
                <tr class="thead-light" style="">
                    <th width="50%">Artist</th>
                    <th>Real Name</th>
                </tr>
            </thead>
            <tbody>
                {% for artist in artists %}
                <tr>
                    <td><a href="{% url 'musicbox:kind_detail' 'artist' artist.id %}">{{ artist.name }}</a></td>
                    <td>{{ artist.real_name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
    <div class="col-md-12 col-lg-8">
            <h5>Genres<small> : {{ genres.count }}개의 검색결과</small></h5>
            <table class="table table-hover mt-2 border-bottom">
                <thead>
                    <tr class="thead-light" style="">
                        <th>Genre</th>
                    </tr>
                </thead>
                <tbody>
                    {% for genre in genres %}
                        <tr>
                            <td><a href="{% url 'musicbox:kind_detail' 'genre' genre.id %}">{{ genre.name }}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <hr>
        <div class="col-md-12 col-lg-8">
                <h5>Playlist<small> : {{ playlists.count }}개의 검색결과</small></h5>
                <table class="table table-hover mt-2 border-bottom">
                    <thead>
                        <tr class="thead-light" style="">
                            <th>Playlists</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for playlist in playlists %}
                            <tr>
                                <td><a href="{% url 'musicbox:kind_detail' 'playlist' playlist.id %}">{{ playlist.name }}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <hr>

{% endblock %}

musicbox/templates/musicbox/song_detail.html
{% extends 'musicbox/base.html' %}

{% block title %}
Song Detail
{% endblock %}

{% block content %}
<div class="jumbotron pb-4 pt-2 m-3">
    <h1 class="display-5 song-title mt-2">{{ song.title }}</h1>
    <hr>
    <p class="lead text-right">
        {% for artist in song.artist.all %}
        <a href="{% url 'musicbox:kind_detail' 'artist' artist.id %}">{{ artist }}</a>{% if not forloop.last %},
        {% endif %}{% endfor %}<br />
        <a href="{% url 'musicbox:kind_detail' 'genre' song.genre.id %}">{{ song.genre }}</a><br />
    </p>
    <div style="position:relative;padding-top:56.25%;">
        <iframe id="{{song.id}}" frameborder="0" allowfullscreen="1"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" title="YouTube video player"
            src="https://www.youtube.com/embed/{{ song.link }}"
            style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
    </div>
</div>
<div class="mt-5 container">
    <h5>이 노래가 있는 Playlist<small> : {{ playlists.count }} Playlist</small></h5>
    {% if playlists %}
        <table class="table table-hover border-bottom">
            <thead>
                <tr class="thead-light" style="">
                    <th>Playlist</th>
                </tr>
            </thead>
            <tbody>
                {% for playlist in playlists %}
                <tr>
                    <td><a href="{% url 'musicbox:kind_detail' 'playlist' 1 %}">{{ playlist.name }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
</div>

{% endblock %}

musicbox/templates/musicbox/song_list.html
{% extends 'musicbox/base.html' %}

{% block title %}
Song List
{% endblock %}

{% block content %}
<div class="p-2 m-3">
    <h1 class="kind-title display-5">Song List</h1>
</div>
{% include 'musicbox/card_style.html' %}

<div class="col-12">
    {% include 'musicbox/pagination.html' %}
</div>

{% endblock %}